title: "Sublime Merge Test"
description: |
  Sublime Merge Test v1080
host: "localhost"
port: 4200

author: 
  name: thecodechef
  email: cyberchefjay@gmail.com

css:
  bulma:
    cdn: "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"
  main:
    file: "assets/css/main.css"
js:  
  font_awesome:
    cdn: "https://use.fontawesome.com/releases/v5.3.1/js/all.js"
  main:
    file: "assets/js/main.js"